name: PMD Static Code Analysis

on:
  push:
    branches:
      - master

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'  # or any other supported distribution like 'adopt', 'adopt-hotspot', etc.
        java-version: '11'     # Adjust the Java version as needed
        java-package: 'jdk'
        architecture: 'x64'
        check-latest: false
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        job-status: success

    - name: Run PMD Analysis
      run: |
        wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.41.0/pmd-bin-6.41.0.zip
        unzip pmd-bin-6.41.0.zip
        ./pmd-bin-6.41.0/bin/run.sh pmd -d <path_to_source_code> -f text -R <rule_set> -reportfile pmd_report.txt
